# Generated by Django 5.2.1 on 2026-04-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="has_approval_permissions",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user should be able to approve curations as an expert panel member.",
                verbose_name="Approval Permissions",
            ),
        ),
    ]
