# Generated by Django 6.0.6 on 2026-07-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_", "0003_historicaluserprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluserprofile",
            name="has_review_permissions",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user can act as an EP reviewer.",
                verbose_name="EP Review Permissions",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="has_review_permissions",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user can act as an EP reviewer.",
                verbose_name="EP Review Permissions",
            ),
        ),
    ]
