# Generated by Django 6.0.6 on 2026-09-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_", "0004_historicaluserprofile_has_review_permissions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluserprofile",
            name="clerk_user_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="The Clerk user ID for this account; populated on first Clerk login.",
                max_length=255,
                null=True,
                verbose_name="Clerk User ID",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="clerk_user_id",
            field=models.CharField(
                blank=True,
                help_text="The Clerk user ID for this account; populated on first Clerk login.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Clerk User ID",
            ),
        ),
    ]
