# Generated by Django 5.2.1 on 2025-07-02 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("allele", "0003_alter_allele_car_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Haplotype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="",
                        help_text="The name of the HLA haplotype in chromosomal mapping order.",
                        max_length=300,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "car_id",
                    models.CharField(
                        blank=True,
                        help_text="ClinGen Allele Registry ID, e.g., XAHLA718827727.",
                        max_length=28,
                        null=True,
                        unique=True,
                        verbose_name="CAR ID",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the haplotype was added.",
                        verbose_name="Added At",
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who added the haplotype.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="haplotypes_added",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Added By",
                    ),
                ),
                (
                    "alleles",
                    models.ManyToManyField(
                        db_table="haplotype_allele_map",
                        related_name="haplotypes",
                        to="allele.allele",
                    ),
                ),
            ],
        ),
    ]
