# Generated by Django 5.2.1 on 2025-07-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haplotype", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="haplotype",
            name="name",
            field=models.CharField(
                default="",
                help_text="The name of the HLA haplotype, e.g., DRB1*15:01~DQB1*06:02. (The 'HLA-' part should be omitted.)",
                max_length=240,
                unique=True,
                verbose_name="Name",
            ),
        ),
    ]
