# Generated by Django 6.0.6 on 2026-06-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haplotype", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="haplotype",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="When the haplotype was last updated.",
                verbose_name="Updated At",
            ),
        ),
    ]
