# Generated by Django 5.2.1 on 2025-07-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allele", "0003_alter_allele_car_id"),
        ("haplotype", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="haplotype",
            name="alleles",
            field=models.ManyToManyField(
                db_table="haplotype_allele_map",
                help_text="The constituent alleles of the haplotype. Saved in chromosomal mapping order.",
                related_name="haplotypes",
                to="allele.allele",
            ),
        ),
        migrations.AlterField(
            model_name="haplotype",
            name="name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The name of the HLA haplotype in chromosomal mapping order.",
                max_length=300,
                unique=True,
                verbose_name="Name",
            ),
        ),
    ]
