# Generated by Django 5.2.1 on 2025-07-03 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("haplotype", "0002_alter_haplotype_alleles_alter_haplotype_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="haplotype",
            name="name",
        ),
    ]
