# Generated by Django 5.2.1 on 2025-07-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allele", "0003_alter_allele_car_id"),
        ("haplotype", "0003_remove_haplotype_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="haplotype",
            options={"verbose_name": "Haplotype", "verbose_name_plural": "Haplotypes"},
        ),
        migrations.AlterField(
            model_name="haplotype",
            name="alleles",
            field=models.ManyToManyField(
                db_table="haplotype_allele_map",
                help_text="The constituent alleles of the haplotype.",
                related_name="haplotypes",
                to="allele.allele",
            ),
        ),
        migrations.AlterModelTable(
            name="haplotype",
            table="haplotype",
        ),
    ]
