# Generated by Django 5.2.1 on 2025-08-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haplotype", "0004_remove_haplotype_hrid"),
    ]

    operations = [
        migrations.AddField(
            model_name="haplotype",
            name="slug",
            field=models.SlugField(
                default="",
                help_text="The human-readable ID for the object.",
                max_length=7,
                verbose_name="Human-Readable ID",
            ),
        ),
    ]
