# Generated by Django 5.2.1 on 2025-06-21 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "publication_type",
                    models.CharField(
                        default="",
                        help_text="One of: 'PUB' (PubMed), 'BIO' (bioRxiv), or 'MED' (medRxiv).",
                        max_length=3,
                        verbose_name="Publication Type",
                    ),
                ),
                (
                    "doi",
                    models.CharField(
                        default="",
                        help_text="The DOI for the publication, e.g., 10.1000/182.",
                        max_length=128,
                        unique=True,
                        verbose_name="Digital Object Identifier (DOI)",
                    ),
                ),
                (
                    "pubmed_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The PubMed ID for the publication, e.g., 11910336. (Required for PubMed articles.)",
                        max_length=16,
                        unique=True,
                        verbose_name="PubMed ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The title of the publication.",
                        max_length=256,
                        verbose_name="Title",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The surname of the primary author of the publication.",
                        max_length=16,
                        verbose_name="Author",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the publication was added.",
                        verbose_name="Added At",
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user that added the publication.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publications_added",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Added By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Publication",
                "verbose_name_plural": "Publications",
                "db_table": "publication",
            },
        ),
    ]
