# Generated by Django 5.2.1 on 2025-06-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "publication",
            "0002_alter_publication_added_by_alter_publication_doi_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="doi",
            field=models.CharField(
                blank=True,
                help_text="The DOI for the publication, e.g., 10.1000/182.",
                max_length=128,
                null=True,
                unique=True,
                verbose_name="Digital Object Identifier (DOI)",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="pubmed_id",
            field=models.CharField(
                blank=True,
                help_text="The PubMed ID for the publication, e.g., 11910336.",
                max_length=16,
                null=True,
                unique=True,
                verbose_name="PubMed ID",
            ),
        ),
    ]
