# Generated by Django 6.0.6 on 2026-06-15 21:44

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publication", "0002_publication_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalPublication",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        default="",
                        help_text="The human-readable ID for the object.",
                        max_length=7,
                        verbose_name="Human-Readable ID",
                    ),
                ),
                (
                    "publication_type",
                    models.CharField(
                        choices=[
                            ("PUB", "PubMed Article"),
                            ("BIO", "bioRxiv Paper"),
                            ("MED", "medRxiv Paper"),
                        ],
                        default="PUB",
                        help_text="One of: 'PUB' (PubMed), 'BIO' (bioRxiv), or 'MED' (medRxiv).",
                        max_length=3,
                        verbose_name="Publication Type",
                    ),
                ),
                (
                    "pubmed_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="The PubMed ID for the publication, e.g., 11910336.",
                        max_length=16,
                        null=True,
                        verbose_name="PubMed ID",
                    ),
                ),
                (
                    "doi",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="The DOI for the publication, e.g., 10.1000/182.",
                        max_length=128,
                        null=True,
                        verbose_name="Digital Object Identifier (DOI)",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The title of the publication.",
                        max_length=256,
                        verbose_name="Title",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The surname of the primary author of the publication.",
                        max_length=16,
                        verbose_name="Author",
                    ),
                ),
                (
                    "publication_year",
                    models.IntegerField(
                        blank=True,
                        help_text="The year the publication was published, e.g., 1999.",
                        null=True,
                        verbose_name="Publication Year",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="When the publication was added.",
                        verbose_name="Added At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="When the publication was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The user who added the publication.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Added By",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Publication",
                "verbose_name_plural": "historical Publications",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
