# Generated by Django 5.2.1 on 2026-02-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publication", "0002_publication_publication_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="publication_year",
            field=models.IntegerField(
                blank=True,
                help_text="The year the publication was published, e.g., 1999.",
                null=True,
                verbose_name="Publication Year",
            ),
        ),
    ]
