# Generated by Django 6.1 on 2026-09-26 02:14

from django.db import migrations, models


def delete_history_without_pubmed_id(apps, schema_editor):
    """Deletes historical records of preprints, which have no PubMed ID.

    Migration 0004 deleted the preprints, but their history rows remain. They would
    block making pubmed_id non-null.
    """
    historical_publication = apps.get_model("publication", "HistoricalPublication")
    historical_publication.objects.filter(pubmed_id__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("publication", "0004_delete_preprint_publications"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpublication",
            name="doi",
        ),
        migrations.RemoveField(
            model_name="historicalpublication",
            name="publication_type",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="doi",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="publication_type",
        ),
        migrations.RunPython(
            delete_history_without_pubmed_id, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="historicalpublication",
            name="pubmed_id",
            field=models.CharField(
                db_index=True,
                help_text="The PubMed ID for the publication, e.g., 11910336.",
                max_length=16,
                verbose_name="PubMed ID",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="pubmed_id",
            field=models.CharField(
                help_text="The PubMed ID for the publication, e.g., 11910336.",
                max_length=16,
                unique=True,
                verbose_name="PubMed ID",
            ),
        ),
    ]
