# Generated by Django 5.2.1 on 2025-08-19 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publication", "0004_publication_hrid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publication",
            name="hrid",
        ),
    ]
