# Generated by Django 5.2.1 on 2025-08-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publication", "0005_remove_publication_hrid"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="slug",
            field=models.SlugField(
                default="",
                help_text="The human-readable ID for the object.",
                max_length=7,
                verbose_name="Human-Readable ID",
            ),
        ),
    ]
