# Generated by Django 5.2.1 on 2026-01-08 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("curation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublishedCuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the curation was published.",
                        verbose_name="Published At",
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1, help_text="Version number for this publication."
                    ),
                ),
                (
                    "curation",
                    models.OneToOneField(
                        help_text="The curation that has been published.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication",
                        to="curation.curation",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        help_text="The user who published the curation.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="curations_published",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Published Curation",
                "verbose_name_plural": "Published Curations",
                "db_table": "published_curation",
                "ordering": ["-published_at"],
            },
        ),
    ]
