# Generated by Django 5.2.1 on 2025-06-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pokedex_number", models.IntegerField(verbose_name="Pokédex Number")),
                ("name", models.CharField(verbose_name="Name")),
                ("type1", models.CharField(verbose_name="Type 1")),
                ("type2", models.CharField(verbose_name="Type 2")),
                ("total", models.IntegerField(verbose_name="Total")),
                ("hp", models.IntegerField(verbose_name="HP")),
                ("attack", models.IntegerField(verbose_name="Attack")),
                ("defense", models.IntegerField(verbose_name="Defense")),
                ("sp_atk", models.IntegerField(verbose_name="Sp. Atk")),
                ("sp_def", models.IntegerField(verbose_name="Sp. Def")),
                ("speed", models.IntegerField(verbose_name="Speed")),
                ("generation", models.IntegerField(verbose_name="Generation")),
                ("legendary", models.BooleanField(verbose_name="Legendary")),
            ],
            options={
                "verbose_name": "Pokémon",
                "verbose_name_plural": "Pokémon",
                "db_table": "pokemon",
            },
        ),
    ]
