# Generated by Django 5.2.1 on 2025-07-01 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("allele", "0003_alter_allele_car_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Curation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "curation_type",
                    models.CharField(
                        choices=[("ALL", "Allele"), ("HAP", "Haplotype")],
                        default="ALL",
                        help_text="Either 'ALL' (allele) or 'HAP' (haplotype).",
                        max_length=3,
                        verbose_name="Curation Type",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the curation was added.",
                        verbose_name="Added At",
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who added the curation.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="curations_added",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Added By",
                    ),
                ),
                (
                    "allele",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="allele.allele",
                    ),
                ),
            ],
            options={
                "verbose_name": "Curation",
                "verbose_name_plural": "Curations",
                "db_table": "curation",
            },
        ),
    ]
