# Generated by Django 5.2.1 on 2026-01-07 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("allele", "0001_initial"),
        ("disease", "0001_initial"),
        ("haplotype", "0001_initial"),
        ("publication", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Demographic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        help_text="The bio-geographical group for a population.",
                        max_length=20,
                        unique=True,
                        verbose_name="Group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demographic",
                "verbose_name_plural": "Demographics",
                "db_table": "demographic",
            },
        ),
        migrations.CreateModel(
            name="Curation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        default="",
                        help_text="The human-readable ID for the object.",
                        max_length=7,
                        verbose_name="Human-Readable ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("INP", "In Progress"), ("DNE", "Done")],
                        default="INP",
                        help_text="Either 'INP' (in progress) or 'DNE' (done).",
                        max_length=3,
                        verbose_name="Status",
                    ),
                ),
                (
                    "curation_type",
                    models.CharField(
                        choices=[("ALL", "Allele"), ("HAP", "Haplotype")],
                        default="ALL",
                        help_text="Either 'ALL' (allele) or 'HAP' (haplotype).",
                        max_length=3,
                        verbose_name="Curation Type",
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("DEF", "Definitive"),
                            ("STR", "Strong"),
                            ("MOD", "Moderate"),
                            ("LIM", "Limited"),
                            ("NOK", "No Known Association"),
                            ("DIS", "Disputed"),
                            ("REF", "Refuted"),
                        ],
                        default="NOK",
                        help_text="The classification level for the curation.",
                        max_length=3,
                        verbose_name="Classification",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the curation was added.",
                        verbose_name="Added At",
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who added the curation.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="curations_added",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Added By",
                    ),
                ),
                (
                    "allele",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select the allele for this curation.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curations",
                        to="allele.allele",
                    ),
                ),
                (
                    "disease",
                    models.ForeignKey(
                        help_text="Select the disease for this curation.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curations",
                        to="disease.disease",
                    ),
                ),
                (
                    "haplotype",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select the haplotype for this curation.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curations",
                        to="haplotype.haplotype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Curation",
                "verbose_name_plural": "Curations",
                "db_table": "curation",
            },
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        default="",
                        help_text="The human-readable ID for the object.",
                        max_length=7,
                        verbose_name="Human-Readable ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("INP", "In Progress"), ("DNE", "Done")],
                        default="INP",
                        help_text="Either 'INP' (in progress) or 'DNE' (done).",
                        max_length=3,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_conflicting",
                    models.BooleanField(
                        default=False,
                        help_text="Is the evidence in this association conflicting?",
                        verbose_name="Conflicts",
                    ),
                ),
                (
                    "is_included",
                    models.BooleanField(
                        default=False,
                        help_text="Should this evidence be included for scoring?",
                        verbose_name="Include",
                    ),
                ),
                (
                    "is_gwas",
                    models.BooleanField(
                        default=False,
                        help_text="Was the study a genome-wide association study?",
                        verbose_name="GWAS",
                    ),
                ),
                (
                    "is_gwas_notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "zygosity",
                    models.CharField(
                        choices=[
                            ("MO", "Monoallelic (heterozygous)"),
                            ("BI", "Biallelic (homozygous)"),
                        ],
                        default="MO",
                        help_text="Either monoallelic (homozygous) or biallelic (heterozygous).",
                        max_length=2,
                        verbose_name="Zygosity",
                    ),
                ),
                (
                    "zygosity_notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "phase_confirmed",
                    models.BooleanField(
                        default=False,
                        help_text="Is the chromosomal phase between alleles at different loci known?",
                        verbose_name="Phase Confirmed",
                    ),
                ),
                (
                    "phase_confirmed_notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "typing_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TAG", "Tagging / Tag SNPs"),
                            ("MIC", "Microarrays"),
                            ("SER", "Serological Typing"),
                            ("IMP", "Imputation"),
                            ("LRT", "Low-Resolution Molecular Genotyping"),
                            ("HRT", "High-Resolution Molecular Genotyping"),
                            ("WES", "Whole Exome Sequencing"),
                            ("RNA", "RNA Sequencing"),
                            ("WGN", "Whole Gene Sequencing"),
                            ("SBT", "Sanger-Sequencing-Based Typing"),
                            ("WGS", "Whole Genome Sequencing"),
                            ("NGS", "Next Generation Sequencing"),
                            ("LRS", "Long Read Sequencing"),
                        ],
                        default="",
                        help_text="The typing method used to determine HLA sequence.",
                        max_length=3,
                        verbose_name="Typing Method",
                    ),
                ),
                (
                    "typing_method_notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "demographics_notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "p_value_string",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The reported p-value as a decimal (e.g. 0.05) or in scientific notation (e.g. 5e-8).",
                        max_length=40,
                        verbose_name="p-value",
                    ),
                ),
                (
                    "p_value",
                    models.DecimalField(
                        decimal_places=30,
                        help_text="The p-value represented as a decimal.",
                        max_digits=40,
                        null=True,
                        verbose_name="p-value Decimal",
                    ),
                ),
                (
                    "p_value_notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "multiple_testing_correction",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OVR", "Overall Correction for Multiple Testing"),
                            ("TWO", "2-step p-value Correction"),
                        ],
                        default="",
                        help_text="Correction for multiple hypothesis testing.",
                        max_length=3,
                        verbose_name="Multiple Testing Correction",
                    ),
                ),
                (
                    "multiple_testing_correction_notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "effect_size_statistic",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OR", "Odds Ratio (OR)"),
                            ("RR", "Relative Risk (RR)"),
                            ("BE", "Beta"),
                            ("OT", "Other"),
                        ],
                        default="",
                        help_text="Select a statistic for the effect size.",
                        max_length=3,
                        verbose_name="Effect Size Statistic",
                    ),
                ),
                (
                    "effect_size_statistic_notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "odds_ratio_string",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The odds ratio as a decimal (e.g. 0.5).",
                        max_length=10,
                        verbose_name="Odds Ratio (OR)",
                    ),
                ),
                (
                    "odds_ratio",
                    models.DecimalField(
                        decimal_places=5,
                        help_text="The odds ratio represented as a decimal.",
                        max_digits=10,
                        null=True,
                        verbose_name="Odds Ratio (OR) Decimal",
                    ),
                ),
                (
                    "relative_risk_string",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The relative risk as a decimal (e.g. 0.5).",
                        max_length=10,
                        verbose_name="Relative Risk (RR)",
                    ),
                ),
                (
                    "relative_risk",
                    models.DecimalField(
                        decimal_places=5,
                        help_text="The relative risk represented as a decimal.",
                        max_digits=10,
                        null=True,
                        verbose_name="Relative Risk (RR) Decimal",
                    ),
                ),
                (
                    "beta_string",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The beta coefficient as a decimal (e.g. 0.5).",
                        max_length=10,
                        verbose_name="Beta Coefficient",
                    ),
                ),
                (
                    "beta",
                    models.DecimalField(
                        decimal_places=5,
                        help_text="The beta coefficient represented as a decimal.",
                        max_digits=10,
                        null=True,
                        verbose_name="Beta Coefficient",
                    ),
                ),
                (
                    "ci_start_string",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The start of the confidence interval as a decimal (e.g. 0.5).",
                        max_length=10,
                        verbose_name="Confidence Interval Start",
                    ),
                ),
                (
                    "ci_start",
                    models.DecimalField(
                        decimal_places=5,
                        help_text="The confidence interval start represented as a decimal.",
                        max_digits=10,
                        null=True,
                        verbose_name="Confidence Interval Start Decimal",
                    ),
                ),
                (
                    "ci_end_string",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The end of the confidence interval as a decimal (e.g. 0.5).",
                        max_length=10,
                        verbose_name="Confidence Interval End",
                    ),
                ),
                (
                    "ci_end",
                    models.DecimalField(
                        decimal_places=5,
                        help_text="The confidence interval end represented as a decimal.",
                        max_digits=10,
                        null=True,
                        verbose_name="Confidence Interval End Decimal",
                    ),
                ),
                (
                    "ci_notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "cohort_size",
                    models.IntegerField(
                        blank=True,
                        help_text="The number of cases added to the number of controls.",
                        null=True,
                        verbose_name="Cohort Size",
                    ),
                ),
                (
                    "cohort_size_notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "additional_phenotypes",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SDR", "Has specific disease-related phenotype"),
                            ("ODT", "Only disease tested"),
                        ],
                        default="",
                        help_text="Whether there is a specific disease-related phenotype.",
                        max_length=3,
                        verbose_name="Additional Phenotypes",
                    ),
                ),
                (
                    "additional_phenotypes_notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "has_association",
                    models.BooleanField(
                        default=True,
                        help_text="Is there a significant association with the disease?",
                        verbose_name="Weighing Association",
                    ),
                ),
                (
                    "has_association_notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "is_protective",
                    models.BooleanField(
                        default=False,
                        help_text="Is the HLA-disease pair protective? Does it decrease risk?",
                        verbose_name="Protective",
                    ),
                ),
                (
                    "is_protective_notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "needs_review",
                    models.BooleanField(
                        default=False,
                        help_text="Does this evidence need to be reviewed manually?",
                        verbose_name="Needs Manual Review",
                    ),
                ),
                (
                    "needs_review_notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the evidence was added.",
                        verbose_name="Added At",
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who added the evidence.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evidence_added",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Added By",
                    ),
                ),
                (
                    "curation",
                    models.ForeignKey(
                        help_text="The curation that the evidence belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="curation.curation",
                    ),
                ),
                (
                    "demographics",
                    models.ManyToManyField(
                        blank=True,
                        db_table="evidence_demographic_map",
                        help_text="The biogeographic groups for the populations in the evidence.",
                        related_name="evidence",
                        to="curation.demographic",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        help_text="The publication that the evidence comes from.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="publication.publication",
                    ),
                ),
            ],
            options={
                "verbose_name": "evidence",
                "verbose_name_plural": "Evidence",
                "db_table": "evidence",
            },
        ),
    ]
