# Generated by Django 5.2.1 on 2026-04-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evidence",
            name="has_association",
            field=models.BooleanField(
                default=False,
                help_text="Is there a significant association with the disease?",
                verbose_name="Weighing Association",
            ),
        ),
    ]
