# Generated by Django 5.2.1 on 2025-07-02 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allele", "0003_alter_allele_car_id"),
        ("curation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curation",
            name="allele",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the allele for this curation.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="allele.allele",
            ),
        ),
    ]
