# Generated by Django 5.2.1 on 2025-07-09 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allele", "0004_alter_allele_name"),
        ("curation", "0001_initial"),
        ("haplotype", "0002_alter_haplotype_name"),
        ("publication", "0003_alter_publication_doi_alter_publication_pubmed_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curation",
            name="allele",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the allele for this curation.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="curations",
                to="allele.allele",
            ),
        ),
        migrations.AlterField(
            model_name="curation",
            name="haplotype",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the haplotype for this curation.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="curations",
                to="haplotype.haplotype",
            ),
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_conflicting",
                    models.BooleanField(
                        default=False,
                        help_text="Is the evidence in this association conflicting?",
                        verbose_name="Conflicts",
                    ),
                ),
                (
                    "is_included",
                    models.BooleanField(
                        default=False,
                        help_text="Should this evidence be included for scoring?",
                        verbose_name="Include",
                    ),
                ),
                (
                    "curation",
                    models.ForeignKey(
                        blank=True,
                        help_text="The curation that the evidence belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence",
                        to="curation.curation",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        help_text="The publication that the evidence comes from.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence",
                        to="publication.publication",
                    ),
                ),
            ],
        ),
    ]
