# Generated by Django 5.2.1 on 2025-07-03 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0002_alter_curation_allele"),
        ("haplotype", "0004_alter_haplotype_options_alter_haplotype_alleles_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="curation",
            name="haplotype",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the haplotype for this curation.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="haplotype.haplotype",
            ),
        ),
    ]
