# Generated by Django 5.2.1 on 2026-04-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0002_alter_evidence_has_association"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="p_value_comparator",
            field=models.CharField(
                blank=True,
                choices=[("", "Exact"), ("LT", "<"), ("LE", "<=")],
                default="",
                help_text="Comparator for the p-value (e.g., <, <=, exact).",
                max_length=2,
                verbose_name="p-value Comparator",
            ),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="p_value_string",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The reported p-value as a decimal (e.g. 0.05), in scientific notation (e.g. 5e-8), or with a comparator (e.g. < 0.0001).",
                max_length=40,
                verbose_name="p-value",
            ),
        ),
    ]
