# Generated by Django 5.2.1 on 2025-07-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0002_alter_curation_allele_alter_curation_haplotype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("INP", "In Progress"), ("DNE", "Done")],
                default="INP",
                help_text="Either 'INP' (in progress) or 'DNE' (done).",
                max_length=3,
                verbose_name="Evidence Status",
            ),
        ),
    ]
