# Generated by Django 5.2.1 on 2026-04-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0003_add_p_value_comparator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evidence",
            name="p_value_comparator",
            field=models.CharField(
                blank=True,
                choices=[("EX", "Exact"), ("LT", "<"), ("LE", "<=")],
                default="",
                help_text="Comparator for the p-value (e.g., <, <=, exact).",
                max_length=2,
                verbose_name="p-value Comparator",
            ),
        ),
    ]
