# Generated by Django 5.2.1 on 2025-07-03 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allele", "0003_alter_allele_car_id"),
        ("curation", "0003_curation_haplotype"),
        ("haplotype", "0004_alter_haplotype_options_alter_haplotype_alleles_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curation",
            name="allele",
            field=models.ForeignKey(
                help_text="Select the allele for this curation.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="allele.allele",
            ),
        ),
        migrations.AlterField(
            model_name="curation",
            name="haplotype",
            field=models.ForeignKey(
                help_text="Select the haplotype for this curation.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="haplotype.haplotype",
            ),
        ),
    ]
