# Generated by Django 5.2.1 on 2025-07-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0003_evidence_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evidence",
            name="status",
            field=models.CharField(
                choices=[("INP", "In Progress"), ("DNE", "Done")],
                default="INP",
                help_text="Either 'INP' (in progress) or 'DNE' (done).",
                max_length=3,
                verbose_name="Evidence Status",
            ),
        ),
    ]
