# Generated by Django 5.2.1 on 2026-04-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0004_alter_evidence_p_value_comparator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curation",
            name="status",
            field=models.CharField(
                choices=[
                    ("INP", "In Progress"),
                    ("PRV", "Provisional"),
                    ("APR", "Approved"),
                    ("PUB", "Published"),
                ],
                default="INP",
                help_text="One of 'INP' (in progress), 'PRV' (provisional), 'APR' (approved), or 'PUB' (published).",
                max_length=3,
                verbose_name="Status",
            ),
        ),
    ]
