# Generated by Django 5.2.1 on 2025-07-10 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0004_alter_evidence_status"),
        ("publication", "0003_alter_publication_doi_alter_publication_pubmed_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evidence",
            name="curation",
            field=models.ForeignKey(
                help_text="The curation that the evidence belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidence",
                to="curation.curation",
            ),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="publication",
            field=models.ForeignKey(
                help_text="The publication that the evidence comes from.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidence",
                to="publication.publication",
            ),
        ),
    ]
