# Generated by Django 6.0.6 on 2026-06-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0004_alter_evidence_p_value_comparator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evidence",
            name="needs_review",
            field=models.BooleanField(
                default=True,
                help_text="Does this evidence need to be reviewed manually?",
                verbose_name="Needs Manual Review",
            ),
        ),
    ]
