# Generated by Django 5.2.1 on 2025-07-10 21:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0005_alter_evidence_curation_alter_evidence_publication"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="added_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="When the evidence was added.",
                verbose_name="Added At",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evidence",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who added the evidence.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evidence_added",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Added By",
            ),
        ),
    ]
