# Generated by Django 5.2.1 on 2026-04-24 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0005_alter_curation_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="curation",
            name="classification_override_reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The reason the expert panel overrode the computed classification.",
                verbose_name="Classification Override Reason",
            ),
        ),
        migrations.AddField(
            model_name="curation",
            name="expert_panel_approved_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the expert panel approved the curation.",
                null=True,
                verbose_name="Expert Panel Approved At",
            ),
        ),
        migrations.AddField(
            model_name="curation",
            name="expert_panel_approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The expert panel member who approved the curation.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="curations_approved",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Expert Panel Approved By",
            ),
        ),
        migrations.AddField(
            model_name="curation",
            name="expert_panel_review_notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Notes recorded by the expert panel during review.",
                verbose_name="Expert Panel Review Notes",
            ),
        ),
    ]
