# Generated by Django 6.0.6 on 2026-06-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0005_alter_evidence_needs_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="curation",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="When the curation was last updated.",
                verbose_name="Updated At",
            ),
        ),
        migrations.AddField(
            model_name="demographic",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="When the demographic was last updated.",
                verbose_name="Updated At",
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="When the evidence was last updated.",
                verbose_name="Updated At",
            ),
        ),
    ]
