# Generated by Django 6.0.6 on 2026-06-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0006_curation_updated_at_demographic_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="num_fields",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1-Field"),
                    (2, "2-Field"),
                    (3, "3-Field, G-Group, P-Group"),
                    (4, "4-Field"),
                ],
                help_text="The allele resolution (number of fields) for the allele or haplotype in the study.",
                null=True,
                verbose_name="Number of Fields",
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="num_fields_notes",
            field=models.TextField(blank=True, default="", verbose_name="Notes"),
        ),
    ]
