# Generated by Django 5.2.1 on 2026-04-24 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0006_curation_classification_override_reason_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CurationStatusEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("INP", "In Progress"),
                            ("PRV", "Provisional"),
                            ("APR", "Approved"),
                            ("PUB", "Published"),
                        ],
                        help_text="The status the curation transitioned from.",
                        max_length=3,
                        verbose_name="From Status",
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("INP", "In Progress"),
                            ("PRV", "Provisional"),
                            ("APR", "Approved"),
                            ("PUB", "Published"),
                        ],
                        help_text="The status the curation transitioned to.",
                        max_length=3,
                        verbose_name="To Status",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="An optional note recorded with the status change.",
                        verbose_name="Note",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the status change was recorded.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who initiated the status change.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="curation_status_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actor",
                    ),
                ),
                (
                    "curation",
                    models.ForeignKey(
                        help_text="The curation whose status changed.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_events",
                        to="curation.curation",
                        verbose_name="Curation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Curation Status Event",
                "verbose_name_plural": "Curation Status Events",
                "db_table": "curation_status_event",
                "ordering": ["-created_at"],
            },
        ),
    ]
