# Generated by Django 5.2.1 on 2025-07-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0006_evidence_added_at_evidence_added_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="is_gwas",
            field=models.BooleanField(
                default=False,
                help_text="Was the study a genome-wide association study?",
                verbose_name="GWAS",
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="zygosity",
            field=models.CharField(
                choices=[("MO", "Monoallelic"), ("BI", "Biallelic")],
                default="MO",
                help_text="Either monoallelic (homozygous) or biallelic (heterozygous).",
                max_length=2,
                verbose_name="Zygosity",
            ),
        ),
    ]
