# Generated by Django 6.0.6 on 2026-06-15 21:44

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allele", "0003_historicalallele"),
        ("curation", "0007_evidence_num_fields_evidence_num_fields_notes"),
        ("disease", "0004_historicaldisease"),
        ("haplotype", "0003_historicalhaplotype"),
        ("publication", "0003_historicalpublication"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalCuration",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        default="",
                        help_text="The human-readable ID for the object.",
                        max_length=7,
                        verbose_name="Human-Readable ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("INP", "In Progress"), ("DNE", "Done")],
                        default="INP",
                        help_text="Either 'INP' (in progress) or 'DNE' (done).",
                        max_length=3,
                        verbose_name="Status",
                    ),
                ),
                (
                    "curation_type",
                    models.CharField(
                        choices=[("ALL", "Allele"), ("HAP", "Haplotype")],
                        default="ALL",
                        help_text="Either 'ALL' (allele) or 'HAP' (haplotype).",
                        max_length=3,
                        verbose_name="Curation Type",
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("DEF", "Definitive"),
                            ("STR", "Strong"),
                            ("MOD", "Moderate"),
                            ("LIM", "Limited"),
                            ("NOK", "No Known Association"),
                            ("DIS", "Disputed"),
                            ("REF", "Refuted"),
                        ],
                        default="NOK",
                        help_text="The classification level for the curation.",
                        max_length=3,
                        verbose_name="Classification",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="When the curation was added.",
                        verbose_name="Added At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="When the curation was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The user who added the curation.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Added By",
                    ),
                ),
                (
                    "allele",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Select the allele for this curation.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="allele.allele",
                    ),
                ),
                (
                    "disease",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Select the disease for this curation.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="disease.disease",
                    ),
                ),
                (
                    "haplotype",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Select the haplotype for this curation.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="haplotype.haplotype",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Curation",
                "verbose_name_plural": "historical Curations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDemographic",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        db_index=True,
                        help_text="The bio-geographical group for a population.",
                        max_length=20,
                        verbose_name="Group",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="When the demographic was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Demographic",
                "verbose_name_plural": "historical Demographics",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEvidence",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        default="",
                        help_text="The human-readable ID for the object.",
                        max_length=7,
                        verbose_name="Human-Readable ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("INP", "In Progress"), ("DNE", "Done")],
                        default="INP",
                        help_text="Either 'INP' (in progress) or 'DNE' (done).",
                        max_length=3,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_conflicting",
                    models.BooleanField(
                        default=False,
                        help_text="Is the evidence in this association conflicting?",
                        verbose_name="Conflicts",
                    ),
                ),
                (
                    "is_included",
                    models.BooleanField(
                        default=False,
                        help_text="Should this evidence be included for scoring?",
                        verbose_name="Include",
                    ),
                ),
                (
                    "is_gwas",
                    models.BooleanField(
                        default=False,
                        help_text="Was the study a genome-wide association study?",
                        verbose_name="GWAS",
                    ),
                ),
                (
                    "is_gwas_notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "num_fields",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1-Field"),
                            (2, "2-Field"),
                            (3, "3-Field, G-Group, P-Group"),
                            (4, "4-Field"),
                        ],
                        help_text="The allele resolution (number of fields) for the allele or haplotype in the study.",
                        null=True,
                        verbose_name="Number of Fields",
                    ),
                ),
                (
                    "num_fields_notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "zygosity",
                    models.CharField(
                        choices=[
                            ("MO", "Monoallelic (heterozygous)"),
                            ("BI", "Biallelic (homozygous)"),
                        ],
                        default="MO",
                        help_text="Either monoallelic (homozygous) or biallelic (heterozygous).",
                        max_length=2,
                        verbose_name="Zygosity",
                    ),
                ),
                (
                    "zygosity_notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "phase_confirmed",
                    models.BooleanField(
                        default=False,
                        help_text="Is the chromosomal phase between alleles at different loci known?",
                        verbose_name="Phase Confirmed",
                    ),
                ),
                (
                    "phase_confirmed_notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "typing_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TAG", "Tagging / Tag SNPs"),
                            ("MIC", "Microarrays"),
                            ("SER", "Serological Typing"),
                            ("IMP", "Imputation"),
                            ("LRT", "Low-Resolution Molecular Genotyping"),
                            ("HRT", "High-Resolution Molecular Genotyping"),
                            ("WES", "Whole Exome Sequencing"),
                            ("RNA", "RNA Sequencing"),
                            ("WGN", "Whole Gene Sequencing"),
                            ("SBT", "Sanger-Sequencing-Based Typing"),
                            ("WGS", "Whole Genome Sequencing"),
                            ("NGS", "Next Generation Sequencing"),
                            ("LRS", "Long Read Sequencing"),
                        ],
                        default="",
                        help_text="The typing method used to determine HLA sequence.",
                        max_length=3,
                        verbose_name="Typing Method",
                    ),
                ),
                (
                    "typing_method_notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "demographics_notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "p_value_string",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The reported p-value as a decimal (e.g. 0.05), in scientific notation (e.g. 5e-8), or with a comparator (e.g. < 0.0001).",
                        max_length=40,
                        verbose_name="p-value",
                    ),
                ),
                (
                    "p_value_comparator",
                    models.CharField(
                        blank=True,
                        choices=[("EX", "Exact"), ("LT", "<"), ("LE", "<=")],
                        default="",
                        help_text="Comparator for the p-value (e.g., <, <=, exact).",
                        max_length=2,
                        verbose_name="p-value Comparator",
                    ),
                ),
                (
                    "p_value",
                    models.DecimalField(
                        decimal_places=30,
                        help_text="The p-value represented as a decimal.",
                        max_digits=40,
                        null=True,
                        verbose_name="p-value Decimal",
                    ),
                ),
                (
                    "p_value_notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "multiple_testing_correction",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OVR", "Overall Correction for Multiple Testing"),
                            ("TWO", "2-step p-value Correction"),
                        ],
                        default="",
                        help_text="Correction for multiple hypothesis testing.",
                        max_length=3,
                        verbose_name="Multiple Testing Correction",
                    ),
                ),
                (
                    "multiple_testing_correction_notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "effect_size_statistic",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OR", "Odds Ratio (OR)"),
                            ("RR", "Relative Risk (RR)"),
                            ("BE", "Beta"),
                            ("OT", "Other"),
                        ],
                        default="",
                        help_text="Select a statistic for the effect size.",
                        max_length=3,
                        verbose_name="Effect Size Statistic",
                    ),
                ),
                (
                    "effect_size_statistic_notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "odds_ratio_string",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The odds ratio as a decimal (e.g. 0.5).",
                        max_length=10,
                        verbose_name="Odds Ratio (OR)",
                    ),
                ),
                (
                    "odds_ratio",
                    models.DecimalField(
                        decimal_places=5,
                        help_text="The odds ratio represented as a decimal.",
                        max_digits=10,
                        null=True,
                        verbose_name="Odds Ratio (OR) Decimal",
                    ),
                ),
                (
                    "relative_risk_string",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The relative risk as a decimal (e.g. 0.5).",
                        max_length=10,
                        verbose_name="Relative Risk (RR)",
                    ),
                ),
                (
                    "relative_risk",
                    models.DecimalField(
                        decimal_places=5,
                        help_text="The relative risk represented as a decimal.",
                        max_digits=10,
                        null=True,
                        verbose_name="Relative Risk (RR) Decimal",
                    ),
                ),
                (
                    "beta_string",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The beta coefficient as a decimal (e.g. 0.5).",
                        max_length=10,
                        verbose_name="Beta Coefficient",
                    ),
                ),
                (
                    "beta",
                    models.DecimalField(
                        decimal_places=5,
                        help_text="The beta coefficient represented as a decimal.",
                        max_digits=10,
                        null=True,
                        verbose_name="Beta Coefficient",
                    ),
                ),
                (
                    "ci_start_string",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The start of the confidence interval as a decimal (e.g. 0.5).",
                        max_length=10,
                        verbose_name="Confidence Interval Start",
                    ),
                ),
                (
                    "ci_start",
                    models.DecimalField(
                        decimal_places=5,
                        help_text="The confidence interval start represented as a decimal.",
                        max_digits=10,
                        null=True,
                        verbose_name="Confidence Interval Start Decimal",
                    ),
                ),
                (
                    "ci_end_string",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The end of the confidence interval as a decimal (e.g. 0.5).",
                        max_length=10,
                        verbose_name="Confidence Interval End",
                    ),
                ),
                (
                    "ci_end",
                    models.DecimalField(
                        decimal_places=5,
                        help_text="The confidence interval end represented as a decimal.",
                        max_digits=10,
                        null=True,
                        verbose_name="Confidence Interval End Decimal",
                    ),
                ),
                (
                    "ci_notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "cohort_size",
                    models.IntegerField(
                        blank=True,
                        help_text="The number of cases added to the number of controls.",
                        null=True,
                        verbose_name="Cohort Size",
                    ),
                ),
                (
                    "cohort_size_notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "additional_phenotypes",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SDR", "Has specific disease-related phenotype"),
                            ("ODT", "Only disease tested"),
                        ],
                        default="",
                        help_text="Whether there is a specific disease-related phenotype.",
                        max_length=3,
                        verbose_name="Additional Phenotypes",
                    ),
                ),
                (
                    "additional_phenotypes_notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "has_association",
                    models.BooleanField(
                        default=False,
                        help_text="Is there a significant association with the disease?",
                        verbose_name="Weighing Association",
                    ),
                ),
                (
                    "has_association_notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "is_protective",
                    models.BooleanField(
                        default=False,
                        help_text="Is the HLA-disease pair protective? Does it decrease risk?",
                        verbose_name="Protective",
                    ),
                ),
                (
                    "is_protective_notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "needs_review",
                    models.BooleanField(
                        default=True,
                        help_text="Does this evidence need to be reviewed manually?",
                        verbose_name="Needs Manual Review",
                    ),
                ),
                (
                    "needs_review_notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="When the evidence was added.",
                        verbose_name="Added At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="When the evidence was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The user who added the evidence.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Added By",
                    ),
                ),
                (
                    "curation",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The curation that the evidence belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="curation.curation",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The publication that the evidence comes from.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="publication.publication",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical evidence",
                "verbose_name_plural": "historical Evidence",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
