# Generated by Django 5.2.1 on 2025-07-12 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0007_evidence_is_gwas_evidence_zygosity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="evidence",
            options={"verbose_name": "evidence", "verbose_name_plural": "Evidence"},
        ),
        migrations.AlterModelTable(
            name="evidence",
            table="evidence",
        ),
    ]
