# Generated by Django 6.0.6 on 2026-07-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0008_historicalcuration_historicaldemographic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="demographics_text_quotes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Relevant quotes from the article about the demographics of the populations studied.",
                verbose_name="Text Quotes",
            ),
        ),
        migrations.AddField(
            model_name="historicalevidence",
            name="demographics_text_quotes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Relevant quotes from the article about the demographics of the populations studied.",
                verbose_name="Text Quotes",
            ),
        ),
    ]
