# Generated by Django 5.2.1 on 2025-07-13 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0009_curation_disease_alter_curation_allele_and_more"),
        ("disease", "0004_remove_disease_ols_iri_disease_iri"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curation",
            name="disease",
            field=models.ForeignKey(
                help_text="Select the disease for this curation.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="curations",
                to="disease.disease",
            ),
        ),
    ]
