# Generated by Django 6.0.6 on 2026-07-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0009_evidence_demographics_text_quotes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evidence",
            name="demographics_text_quotes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Relevant quotes from the publication about the demographics of the populations studied.",
                verbose_name="Text Quotes",
            ),
        ),
        migrations.AlterField(
            model_name="historicalevidence",
            name="demographics_text_quotes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Relevant quotes from the publication about the demographics of the populations studied.",
                verbose_name="Text Quotes",
            ),
        ),
    ]
