# Generated by Django 5.2.1 on 2025-07-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0010_alter_curation_disease"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="is_gwas_notes",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="evidence",
            name="zygosity_notes",
            field=models.TextField(default=""),
        ),
    ]
