# Generated by Django 6.0.6 on 2026-07-29 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0010_alter_evidence_demographics_text_quotes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curation",
            name="classification",
        ),
        migrations.RemoveField(
            model_name="historicalcuration",
            name="classification",
        ),
        migrations.AddField(
            model_name="curation",
            name="ep",
            field=models.CharField(
                blank=True,
                help_text="Five-digit numeric ID of the expert panel.",
                max_length=5,
                null=True,
                verbose_name="Expert Panel",
            ),
        ),
        migrations.AddField(
            model_name="curation",
            name="ep_classification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEF", "Definitive"),
                    ("STR", "Strong"),
                    ("MOD", "Moderate"),
                    ("LIM", "Limited"),
                    ("NOK", "No Known Association"),
                    ("DIS", "Disputed"),
                    ("REF", "Refuted"),
                ],
                help_text="The classification set by the expert panel at review time.",
                max_length=3,
                null=True,
                verbose_name="EP Classification",
            ),
        ),
        migrations.AddField(
            model_name="curation",
            name="ep_classification_notes",
            field=models.TextField(
                blank=True,
                help_text="The expert panel's written reasoning for the classification.",
                null=True,
                verbose_name="EP Classification Notes",
            ),
        ),
        migrations.AddField(
            model_name="curation",
            name="ep_notes",
            field=models.TextField(
                blank=True,
                help_text="Additional notes from the expert panel.",
                null=True,
                verbose_name="EP Notes",
            ),
        ),
        migrations.AddField(
            model_name="curation",
            name="forked_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forks",
                to="curation.curation",
            ),
        ),
        migrations.AddField(
            model_name="curation",
            name="in_progress_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="curation",
            name="provisional_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="curation",
            name="ready_for_review_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcuration",
            name="ep",
            field=models.CharField(
                blank=True,
                help_text="Five-digit numeric ID of the expert panel.",
                max_length=5,
                null=True,
                verbose_name="Expert Panel",
            ),
        ),
        migrations.AddField(
            model_name="historicalcuration",
            name="ep_classification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEF", "Definitive"),
                    ("STR", "Strong"),
                    ("MOD", "Moderate"),
                    ("LIM", "Limited"),
                    ("NOK", "No Known Association"),
                    ("DIS", "Disputed"),
                    ("REF", "Refuted"),
                ],
                help_text="The classification set by the expert panel at review time.",
                max_length=3,
                null=True,
                verbose_name="EP Classification",
            ),
        ),
        migrations.AddField(
            model_name="historicalcuration",
            name="ep_classification_notes",
            field=models.TextField(
                blank=True,
                help_text="The expert panel's written reasoning for the classification.",
                null=True,
                verbose_name="EP Classification Notes",
            ),
        ),
        migrations.AddField(
            model_name="historicalcuration",
            name="ep_notes",
            field=models.TextField(
                blank=True,
                help_text="Additional notes from the expert panel.",
                null=True,
                verbose_name="EP Notes",
            ),
        ),
        migrations.AddField(
            model_name="historicalcuration",
            name="forked_from",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="curation.curation",
            ),
        ),
        migrations.AddField(
            model_name="historicalcuration",
            name="in_progress_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcuration",
            name="provisional_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcuration",
            name="ready_for_review_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="curation",
            name="status",
            field=models.CharField(
                choices=[
                    ("INP", "In Progress"),
                    ("RFR", "Ready for Review"),
                    ("PRO", "Provisional"),
                ],
                default="INP",
                help_text="The current lifecycle status of the curation.",
                max_length=3,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="demographics_text_quotes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Relevant quotes from the publication about the demographics.",
                verbose_name="Text Quotes",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcuration",
            name="status",
            field=models.CharField(
                choices=[
                    ("INP", "In Progress"),
                    ("RFR", "Ready for Review"),
                    ("PRO", "Provisional"),
                ],
                default="INP",
                help_text="The current lifecycle status of the curation.",
                max_length=3,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalevidence",
            name="demographics_text_quotes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Relevant quotes from the publication about the demographics.",
                verbose_name="Text Quotes",
            ),
        ),
    ]
