# Generated by Django 5.2.1 on 2025-07-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0011_evidence_is_gwas_notes_evidence_zygosity_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="curation",
            name="status",
            field=models.CharField(
                choices=[("INP", "In Progress"), ("DNE", "Done")],
                default="INP",
                help_text="Either 'INP' (in progress) or 'DNE' (done).",
                max_length=3,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="is_gwas_notes",
            field=models.TextField(blank=True, default="", verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="zygosity",
            field=models.CharField(
                choices=[
                    ("MO", "Monoallelic (heterozygous)"),
                    ("BI", "Biallelic (homozygous)"),
                ],
                default="MO",
                help_text="Either monoallelic (homozygous) or biallelic (heterozygous).",
                max_length=2,
                verbose_name="Zygosity",
            ),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="zygosity_notes",
            field=models.TextField(blank=True, default="", verbose_name="Notes"),
        ),
    ]
