# Generated by Django 6.0.6 on 2026-07-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0011_remove_curation_classification_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curation",
            name="ep_classification_notes",
        ),
        migrations.RemoveField(
            model_name="curation",
            name="ep_notes",
        ),
        migrations.RemoveField(
            model_name="historicalcuration",
            name="ep_classification_notes",
        ),
        migrations.RemoveField(
            model_name="historicalcuration",
            name="ep_notes",
        ),
        migrations.AddField(
            model_name="curation",
            name="ep_additional_notes",
            field=models.TextField(
                blank=True,
                help_text="Additional notes from the expert panel.",
                null=True,
                verbose_name="EP Additional Notes",
            ),
        ),
        migrations.AddField(
            model_name="curation",
            name="ep_evidence_summary",
            field=models.TextField(
                blank=True,
                help_text="The expert panel's written reasoning for the classification.",
                null=True,
                verbose_name="EP Evidence Summary",
            ),
        ),
        migrations.AddField(
            model_name="historicalcuration",
            name="ep_additional_notes",
            field=models.TextField(
                blank=True,
                help_text="Additional notes from the expert panel.",
                null=True,
                verbose_name="EP Additional Notes",
            ),
        ),
        migrations.AddField(
            model_name="historicalcuration",
            name="ep_evidence_summary",
            field=models.TextField(
                blank=True,
                help_text="The expert panel's written reasoning for the classification.",
                null=True,
                verbose_name="EP Evidence Summary",
            ),
        ),
    ]
