# Generated by Django 6.0.6 on 2026-07-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0012_remove_curation_ep_classification_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curation",
            name="ep_evidence_summary",
            field=models.TextField(
                blank=True,
                help_text="The expert panel's summary of the evidence.",
                null=True,
                verbose_name="EP Evidence Summary",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcuration",
            name="ep_evidence_summary",
            field=models.TextField(
                blank=True,
                help_text="The expert panel's summary of the evidence.",
                null=True,
                verbose_name="EP Evidence Summary",
            ),
        ),
    ]
