# Generated by Django 5.2.1 on 2025-07-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0012_curation_status_alter_evidence_is_gwas_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="curation",
            name="classification",
            field=models.CharField(
                choices=[
                    ("DEF", "Definitive"),
                    ("STR", "Strong"),
                    ("MOD", "Moderate"),
                    ("LIM", "Limited"),
                    ("NOK", "No Known Association"),
                    ("DIS", "Disputed"),
                    ("REF", "Refuted"),
                ],
                default="NOK",
                help_text="The classification level for the curation.",
                max_length=3,
                verbose_name="Classification",
            ),
        ),
    ]
