# Generated by Django 6.0.6 on 2026-08-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0013_alter_curation_ep_evidence_summary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curation",
            name="status",
            field=models.CharField(
                choices=[
                    ("INP", "In Progress"),
                    ("RFR", "Ready for Review"),
                    ("PRO", "Provisional"),
                    ("PUB", "Published"),
                ],
                default="INP",
                help_text="The current lifecycle status of the curation.",
                max_length=3,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcuration",
            name="status",
            field=models.CharField(
                choices=[
                    ("INP", "In Progress"),
                    ("RFR", "Ready for Review"),
                    ("PRO", "Provisional"),
                    ("PUB", "Published"),
                ],
                default="INP",
                help_text="The current lifecycle status of the curation.",
                max_length=3,
                verbose_name="Status",
            ),
        ),
    ]
