# Generated by Django 5.2.1 on 2025-07-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0013_curation_classification"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="phase_confirmed",
            field=models.BooleanField(
                default=False,
                help_text="Is the chromosomal phase between alleles at different loci known?",
                verbose_name="Phase Confirmed",
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="phase_confirmed_notes",
            field=models.TextField(blank=True, default="", verbose_name="Notes"),
        ),
    ]
