# Generated by Django 6.0.6 on 2026-08-05 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0014_add_published_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evidence",
            name="is_conflicting",
        ),
        migrations.RemoveField(
            model_name="historicalevidence",
            name="is_conflicting",
        ),
    ]
