# Generated by Django 5.2.1 on 2025-07-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0014_evidence_phase_confirmed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="typing_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TAG", "Tagging / Tag SNPs"),
                    ("MIC", "Microarrays"),
                    ("SER", "Serological Typing"),
                    ("IMP", "Imputation"),
                    ("LRT", "Low-Resolution Molecular Genotyping"),
                    ("HRT", "High-Resolution Molecular Genotyping"),
                    ("WES", "Whole Exome Sequencing"),
                    ("RNA", "RNA Sequencing"),
                    ("SBT", "Sanger-Sequencing-Based Typing"),
                    ("WGS", "Whole Genome Sequencing"),
                    ("NGS", "Next Generation Sequencing"),
                    ("LRS", "Long Read Sequencing"),
                ],
                default="",
                help_text="The typing method used to determine HLA sequence.",
                max_length=3,
                verbose_name="Typing Method",
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="typing_method_notes",
            field=models.TextField(blank=True, default="", verbose_name="Notes"),
        ),
    ]
