# Generated by Django 6.0.6 on 2026-08-05 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0015_remove_evidence_is_conflicting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curation",
            name="forked_from",
            field=models.ForeignKey(
                blank=True,
                help_text="The published curation this curation was forked from, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forks",
                to="curation.curation",
                verbose_name="Forked From",
            ),
        ),
        migrations.AlterField(
            model_name="curation",
            name="in_progress_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the curation most recently entered the In Progress status.",
                null=True,
                verbose_name="In Progress At",
            ),
        ),
        migrations.AlterField(
            model_name="curation",
            name="provisional_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the curation was approved by the expert panel.",
                null=True,
                verbose_name="Provisional At",
            ),
        ),
        migrations.AlterField(
            model_name="curation",
            name="ready_for_review_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the curation was submitted for expert panel review.",
                null=True,
                verbose_name="Ready for Review At",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcuration",
            name="forked_from",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The published curation this curation was forked from, if any.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="curation.curation",
                verbose_name="Forked From",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcuration",
            name="in_progress_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the curation most recently entered the In Progress status.",
                null=True,
                verbose_name="In Progress At",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcuration",
            name="provisional_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the curation was approved by the expert panel.",
                null=True,
                verbose_name="Provisional At",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcuration",
            name="ready_for_review_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the curation was submitted for expert panel review.",
                null=True,
                verbose_name="Ready for Review At",
            ),
        ),
    ]
