# Generated by Django 5.2.1 on 2025-07-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0015_evidence_typing_method_evidence_typing_method_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="p_value",
            field=models.DecimalField(
                decimal_places=30,
                help_text="The reported p-value.",
                max_digits=40,
                null=True,
                verbose_name="p-value",
            ),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="typing_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TAG", "Tagging / Tag SNPs"),
                    ("MIC", "Microarrays"),
                    ("SER", "Serological typing"),
                    ("IMP", "Imputation"),
                    ("LRT", "Low-resolution molecular genotyping"),
                    ("HRT", "High-resolution molecular genotyping"),
                    ("WES", "Whole exome sequencing"),
                    ("RNA", "RNA sequencing"),
                    ("SBT", "Sanger-sequencing-based typing"),
                    ("WGS", "Whole genome sequencing"),
                    ("NGS", "Next generation sequencing"),
                    ("LRS", "Long read sequencing"),
                ],
                default="",
                help_text="The typing method used to determine HLA sequence.",
                max_length=3,
                verbose_name="Typing Method",
            ),
        ),
    ]
