# Generated by Django 5.2.1 on 2025-07-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0016_evidence_p_value_alter_evidence_typing_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="p_value_notes",
            field=models.TextField(blank=True, default="", verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="p_value",
            field=models.DecimalField(
                decimal_places=30,
                help_text="The reported p-value as a decimal (e.g. 0.05) or in scientific notation (e.g. 5e-8).",
                max_digits=40,
                null=True,
                verbose_name="p-value",
            ),
        ),
    ]
