# Generated by Django 6.0.6 on 2026-08-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0016_add_verbose_names_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="curation",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the curation was published to the repository.",
                null=True,
                verbose_name="Published At",
            ),
        ),
        migrations.AddField(
            model_name="historicalcuration",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the curation was published to the repository.",
                null=True,
                verbose_name="Published At",
            ),
        ),
    ]
