# Generated by Django 5.2.1 on 2025-07-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0017_evidence_p_value_notes_alter_evidence_p_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="p_value_string",
            field=models.CharField(
                default="",
                help_text="The reported p-value as a decimal (e.g. 0.05) or in scientific notation (e.g. 5e-8).",
                max_length=40,
                verbose_name="p-value",
            ),
        ),
    ]
