# Generated by Django 5.2.1 on 2025-07-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0018_evidence_p_value_string"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="multiple_testing_correction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OVR", "Overall correction for multiple testing"),
                    ("TWO", "2-step p-value correction"),
                ],
                default="",
                help_text="Correction for multiple hypothesis testing.",
                max_length=3,
                verbose_name="Multiple Testing Correction",
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="multiple_testing_correction_notes",
            field=models.TextField(blank=True, default="", verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="p_value",
            field=models.DecimalField(
                decimal_places=30,
                help_text="The p-value represented as a decimal.",
                max_digits=40,
                null=True,
                verbose_name="p-value Decimal",
            ),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="p_value_string",
            field=models.CharField(
                default="",
                help_text="The reported p-value as a decimal (e.g. 0.05) or in scientific notation (e.g. 5e-8).",
                max_length=40,
                verbose_name="p-value String",
            ),
        ),
    ]
