# Generated by Django 6.0.6 on 2026-08-12 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0019_rename_forked_from_to_copied_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curation",
            name="copied_from",
            field=models.ForeignKey(
                blank=True,
                help_text="The published curation this curation was copied from, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="copies",
                to="curation.curation",
                verbose_name="Copied From",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcuration",
            name="copied_from",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The published curation this curation was copied from, if any.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="curation.curation",
                verbose_name="Copied From",
            ),
        ),
    ]
