# Generated by Django 5.2.1 on 2025-07-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0019_evidence_multiple_testing_correction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="odds_ratio",
            field=models.DecimalField(
                decimal_places=5,
                help_text="The odds ratio represented as a decimal.",
                max_digits=10,
                null=True,
                verbose_name="Odds Ratio (OR) Decimal",
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="odds_ratio_notes",
            field=models.TextField(blank=True, default="", verbose_name="Notes"),
        ),
        migrations.AddField(
            model_name="evidence",
            name="odds_ratio_string",
            field=models.CharField(
                default="",
                help_text="The odds ratio.",
                max_length=10,
                verbose_name="Odds Ratio (OR) String",
            ),
        ),
    ]
