# Generated by Django 5.2.1 on 2025-07-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0021_evidence_beta_evidence_beta_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evidence",
            name="beta_string",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The beta coefficient.",
                max_length=10,
                verbose_name="Beta Coefficient",
            ),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="odds_ratio_string",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The odds ratio.",
                max_length=10,
                verbose_name="Odds Ratio (OR)",
            ),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="p_value_string",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The reported p-value as a decimal (e.g. 0.05) or in scientific notation (e.g. 5e-8).",
                max_length=40,
                verbose_name="p-value",
            ),
        ),
    ]
