# Generated by Django 6.1 on 2026-09-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0021_rename_status_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="curation",
            name="ep_review_date",
            field=models.DateField(
                blank=True,
                help_text="The date the expert panel reviewed the curation.",
                null=True,
                verbose_name="EP Review Date",
            ),
        ),
        migrations.AddField(
            model_name="historicalcuration",
            name="ep_review_date",
            field=models.DateField(
                blank=True,
                help_text="The date the expert panel reviewed the curation.",
                null=True,
                verbose_name="EP Review Date",
            ),
        ),
    ]
