# Generated by Django 5.2.1 on 2025-07-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0022_alter_evidence_beta_string_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="relative_risk",
            field=models.DecimalField(
                decimal_places=5,
                help_text="The relative risk represented as a decimal.",
                max_digits=10,
                null=True,
                verbose_name="Relative Risk (RR) Decimal",
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="relative_risk_notes",
            field=models.TextField(
                blank=True, default="", verbose_name="Relative Risk (RR) Notes"
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="relative_risk_string",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The relative risk.",
                max_length=10,
                verbose_name="Relative Risk (RR)",
            ),
        ),
    ]
