# Generated by Django 6.1 on 2026-09-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0022_add_curation_ep_review_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="curation",
            name="ep_override_reason",
            field=models.TextField(
                blank=True,
                help_text="Why the panel chose a classification other than the suggested one.",
                null=True,
                verbose_name="EP Override Reason",
            ),
        ),
        migrations.AddField(
            model_name="historicalcuration",
            name="ep_override_reason",
            field=models.TextField(
                blank=True,
                help_text="Why the panel chose a classification other than the suggested one.",
                null=True,
                verbose_name="EP Override Reason",
            ),
        ),
    ]
