# Generated by Django 5.2.1 on 2025-07-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "curation",
            "0023_evidence_relative_risk_evidence_relative_risk_notes_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="effect_size_statistic",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OR", "Odds ratio"),
                    ("RR", "Relative risk"),
                    ("BT", "Beta"),
                    ("OT", "Other"),
                ],
                default="",
                help_text="Select a statistic for the effect size.",
                max_length=3,
                verbose_name="Effect Size Statistic",
            ),
        ),
    ]
