# Generated by Django 5.2.1 on 2025-07-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0024_evidence_effect_size_statistic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evidence",
            name="beta_notes",
        ),
        migrations.RemoveField(
            model_name="evidence",
            name="odds_ratio_notes",
        ),
        migrations.RemoveField(
            model_name="evidence",
            name="relative_risk_notes",
        ),
        migrations.AddField(
            model_name="evidence",
            name="effect_size_statistic_notes",
            field=models.CharField(blank=True, default="", verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="effect_size_statistic",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OR", "Odds Ratio (OR)"),
                    ("RR", "Relative Risk (RR)"),
                    ("BE", "Beta"),
                    ("OT", "Other"),
                ],
                default="",
                help_text="Select a statistic for the effect size.",
                max_length=3,
                verbose_name="Effect Size Statistic",
            ),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="multiple_testing_correction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OVR", "Overall Correction for Multiple Testing"),
                    ("TWO", "2-step p-value Correction"),
                ],
                default="",
                help_text="Correction for multiple hypothesis testing.",
                max_length=3,
                verbose_name="Multiple Testing Correction",
            ),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="typing_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TAG", "Tagging / Tag SNPs"),
                    ("MIC", "Microarrays"),
                    ("SER", "Serological Typing"),
                    ("IMP", "Imputation"),
                    ("LRT", "Low-Resolution Molecular Genotyping"),
                    ("HRT", "High-Resolution Molecular Genotyping"),
                    ("WES", "Whole Exome Sequencing"),
                    ("RNA", "RNA Sequencing"),
                    ("SBT", "Sanger-Sequencing-Based Typing"),
                    ("WGS", "Whole Genome Sequencing"),
                    ("NGS", "Next Generation Sequencing"),
                    ("LRS", "Long Read Sequencing"),
                ],
                default="",
                help_text="The typing method used to determine HLA sequence.",
                max_length=3,
                verbose_name="Typing Method",
            ),
        ),
    ]
