# Generated by Django 5.2.1 on 2025-07-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0025_remove_evidence_beta_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="ci_end",
            field=models.DecimalField(
                decimal_places=5,
                help_text="The confidence interval end represented as a decimal.",
                max_digits=10,
                null=True,
                verbose_name="Confidence Interval End Decimal",
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="ci_end_string",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The end of the confidence interval as a decimal (e.g. 0.5).",
                max_length=10,
                verbose_name="Confidence Interval End",
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="ci_start",
            field=models.DecimalField(
                decimal_places=5,
                help_text="The confidence interval start represented as a decimal.",
                max_digits=10,
                null=True,
                verbose_name="Confidence Interval Start Decimal",
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="ci_start_string",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The start of the confidence interval as a decimal (e.g. 0.5).",
                max_length=10,
                verbose_name="Confidence Interval Start",
            ),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="beta_string",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The beta coefficient as a decimal (e.g. 0.5).",
                max_length=10,
                verbose_name="Beta Coefficient",
            ),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="effect_size_statistic_notes",
            field=models.TextField(blank=True, default="", verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="odds_ratio_string",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The odds ratio as a decimal (e.g. 0.5).",
                max_length=10,
                verbose_name="Odds Ratio (OR)",
            ),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="relative_risk_string",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The relative risk as a decimal (e.g. 0.5).",
                max_length=10,
                verbose_name="Relative Risk (RR)",
            ),
        ),
    ]
