# Generated by Django 5.2.1 on 2025-07-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0026_evidence_ci_end_evidence_ci_end_string_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="ci_notes",
            field=models.TextField(blank=True, default="", verbose_name="Notes"),
        ),
    ]
