# Generated by Django 5.2.1 on 2025-07-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0027_evidence_ci_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="cohort_size",
            field=models.IntegerField(
                blank=True,
                help_text="The number of cases added to the number of controls.",
                null=True,
                verbose_name="Cohort Size",
            ),
        ),
    ]
