# Generated by Django 5.2.1 on 2025-07-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0028_evidence_cohort_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="cohort_size_notes",
            field=models.TextField(blank=True, default="", verbose_name="Notes"),
        ),
    ]
