# Generated by Django 5.2.1 on 2025-07-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0029_evidence_cohort_size_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="additional_phenotypes",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SDR", "Has specific disease-related phenotype"),
                    ("ODT", "Only disease tested"),
                ],
                default="",
                help_text="Whether there is a specific disease-related phenotype.",
                max_length=3,
                verbose_name="Additional Phenotypes",
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="additional_phenotypes_notes",
            field=models.TextField(blank=True, default="", verbose_name="Notes"),
        ),
    ]
