# Generated by Django 5.2.1 on 2025-07-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0030_evidence_additional_phenotypes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="has_association",
            field=models.BooleanField(
                default=True,
                help_text="Is there a significant association with the disease?",
                verbose_name="Weighing Association",
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="has_association_notes",
            field=models.TextField(blank=True, default="", verbose_name="Notes"),
        ),
    ]
