# Generated by Django 5.2.1 on 2025-07-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0032_demographic"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="demographics",
            field=models.ManyToManyField(
                db_table="evidence_demographic_map",
                help_text="The biogeographic groups for the populations in the evidence.",
                related_name="evidence",
                to="curation.demographic",
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="demographics_notes",
            field=models.TextField(blank=True, default="", verbose_name="Notes"),
        ),
    ]
