# Generated by Django 5.2.1 on 2025-07-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0033_evidence_demographics_evidence_demographics_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demographic",
            name="group",
            field=models.CharField(
                help_text="The bio-geographical group for a population.",
                max_length=20,
                unique=True,
                verbose_name="Group",
            ),
        ),
    ]
