# Generated by Django 5.2.1 on 2025-07-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0034_alter_demographic_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="needs_review",
            field=models.BooleanField(
                default=False,
                help_text="Does this evidence need to be reviewed manually?",
                verbose_name="Needs Manual Review",
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="needs_review_notes",
            field=models.TextField(blank=True, default="", verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="demographics",
            field=models.ManyToManyField(
                blank=True,
                db_table="evidence_demographic_map",
                help_text="The biogeographic groups for the populations in the evidence.",
                related_name="evidence",
                to="curation.demographic",
            ),
        ),
    ]
