# Generated by Django 5.2.1 on 2025-08-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0036_alter_evidence_typing_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="curation",
            name="hrid",
            field=models.CharField(
                blank=True,
                help_text="The human readable ID for the object.",
                max_length=7,
                null=True,
                unique=True,
                verbose_name="Human-Readable ID",
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="hrid",
            field=models.CharField(
                blank=True,
                help_text="The human readable ID for the object.",
                max_length=7,
                null=True,
                unique=True,
                verbose_name="Human-Readable ID",
            ),
        ),
    ]
