# Generated by Django 5.2.1 on 2025-08-19 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0037_curation_hrid_evidence_hrid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curation",
            name="hrid",
        ),
        migrations.RemoveField(
            model_name="evidence",
            name="hrid",
        ),
    ]
