# Generated by Django 5.2.1 on 2025-08-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0038_remove_curation_hrid_remove_evidence_hrid"),
    ]

    operations = [
        migrations.AddField(
            model_name="curation",
            name="slug",
            field=models.SlugField(
                default="",
                help_text="The human-readable ID for the object.",
                max_length=7,
                verbose_name="Human-Readable ID",
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="slug",
            field=models.SlugField(
                default="",
                help_text="The human-readable ID for the object.",
                max_length=7,
                verbose_name="Human-Readable ID",
            ),
        ),
    ]
