# Generated by Django 5.2.1 on 2025-08-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0039_curation_slug_evidence_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="is_protective",
            field=models.BooleanField(
                default=False,
                help_text="Whether the HLA-disease pair is protective / decreases risk.",
                verbose_name="Effect Directionality",
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="is_protective_notes",
            field=models.TextField(blank=True, default="", verbose_name="Notes"),
        ),
    ]
