# Generated by Django 5.2.1 on 2026-01-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0040_evidence_is_protective_evidence_is_protective_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evidence",
            name="is_protective",
            field=models.BooleanField(
                default=False,
                help_text="Is the HLA-disease pair protective? Does it decrease risk?",
                verbose_name="Protective",
            ),
        ),
    ]
