# Generated by Django 5.2.1 on 2026-01-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0040_evidence_is_protective_evidence_is_protective_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evidence",
            name="demographics",
        ),
        migrations.AlterField(
            model_name="evidence",
            name="is_protective",
            field=models.BooleanField(
                default=False,
                help_text="Is the HLA-disease pair protective? Does it decrease risk?",
                verbose_name="Protective",
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="demographics",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AME", "American"),
                    ("SAS", "Central/South Asian"),
                    ("EAS", "East Asian"),
                    ("EUR", "European"),
                    ("NEA", "Near Eastern"),
                    ("OCE", "Oceanian"),
                    ("SSA", "Sub-Saharan African"),
                ],
                default="",
                help_text="The biogeographic groups for the populations in the evidence.",
                max_length=3,
                verbose_name="Demographics",
            ),
        ),
    ]
