# Generated by Django 5.2.1 on 2026-01-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0041_remove_evidence_demographics_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evidence",
            name="demographics",
        ),
        migrations.AddField(
            model_name="evidence",
            name="demographics",
            field=models.ManyToManyField(
                blank=True,
                db_table="evidence_demographic_map",
                help_text="The biogeographic groups for the populations in the evidence.",
                related_name="evidence",
                to="curation.demographic",
            ),
        ),
    ]
