# Generated by Django 5.2.1 on 2025-06-24 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who added the publication.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="publications_added",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Added By",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="doi",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The DOI for the publication, e.g., 10.1000/182.",
                max_length=128,
                unique=True,
                verbose_name="Digital Object Identifier (DOI)",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="publication_type",
            field=models.CharField(
                choices=[
                    ("PUB", "PubMed Article"),
                    ("BIO", "bioRxiv Paper"),
                    ("MED", "medRxiv Paper"),
                ],
                default="PUB",
                help_text="One of: 'PUB' (PubMed), 'BIO' (bioRxiv), or 'MED' (medRxiv).",
                max_length=3,
                verbose_name="Publication Type",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="pubmed_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The PubMed ID for the publication, e.g., 11910336.",
                max_length=16,
                unique=True,
                verbose_name="PubMed ID",
            ),
        ),
    ]
