- name: Pull the latest changes on main
  ansible.builtin.git:
    repo: "{{ repo_url }}"
    dest: "{{ repo_dir }}"
    version: "main"
    update: true
- name: Pull the latest changes on the specified branch
  ansible.builtin.git:
    repo: "{{ repo_url }}"
    dest: "{{ repo_dir }}"
    version: "{{ repo_branch }}"
    update: true
