- name: Ensure the Gunicorn systemd socket is started
  become: true
  ansible.builtin.systemd:
    name: gunicorn.socket
    state: started
- name: Ensure the Gunicorn systemd service is started
  become: true
  ansible.builtin.systemd:
    name: gunicorn.service
    state: started
