# Generated by Django 5.2.1 on 2025-06-26 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Disease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disease_type",
                    models.CharField(
                        blank=True,
                        choices=[("MON", "Mondo")],
                        default="MON",
                        help_text="The disease ontology type. Only Mondo (type 'MON') disease are supported for now.",
                        max_length=3,
                        verbose_name="Disease Type",
                    ),
                ),
                (
                    "mondo_id",
                    models.CharField(
                        default="",
                        help_text="The Mondo Disease Ontology ID, e.g., MONDO:1234567.",
                        max_length=26,
                        unique=True,
                        verbose_name="PubMed ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The name of the disease.",
                        max_length=256,
                        verbose_name="Name",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the disease was added.",
                        verbose_name="Added At",
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who added the disease.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diseases_added",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Added By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disease",
                "verbose_name_plural": "Diseases",
                "db_table": "disease",
            },
        ),
    ]
