# Generated by Django 5.2.1 on 2025-06-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disease", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="disease",
            name="ols_iri",
            field=models.CharField(
                blank=True,
                default="",
                max_length=88,
                unique=True,
                verbose_name="Ontology Lookup Service (OLS) Internationalized Resource Identifier (IRI)",
            ),
        ),
        migrations.AlterField(
            model_name="disease",
            name="disease_type",
            field=models.CharField(
                blank=True,
                choices=[("MON", "Mondo")],
                default="MON",
                help_text="The disease ontology type. Only Mondo diseases are supported for now.",
                max_length=3,
                verbose_name="Disease Type",
            ),
        ),
        migrations.AlterField(
            model_name="disease",
            name="mondo_id",
            field=models.CharField(
                default="",
                help_text="The Mondo Disease Ontology ID, e.g., MONDO:1234567.",
                max_length=26,
                unique=True,
                verbose_name="Mondo ID",
            ),
        ),
    ]
