# Generated by Django 6.0.6 on 2026-06-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disease", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disease",
            name="mondo_id",
            field=models.CharField(
                default="",
                help_text="The Mondo Disease Ontology ID, e.g., MONDO:0005052.",
                max_length=26,
                unique=True,
                verbose_name="Mondo ID",
            ),
        ),
    ]
