# Generated by Django 6.0.6 on 2026-06-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disease", "0002_alter_disease_mondo_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="disease",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="When the disease was last updated.",
                verbose_name="Updated At",
            ),
        ),
    ]
