# Generated by Django 6.0.6 on 2026-06-15 21:44

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disease", "0003_disease_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalDisease",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        default="",
                        help_text="The human-readable ID for the object.",
                        max_length=7,
                        verbose_name="Human-Readable ID",
                    ),
                ),
                (
                    "disease_type",
                    models.CharField(
                        blank=True,
                        choices=[("MON", "Mondo")],
                        default="MON",
                        help_text="The disease ontology type. Only Mondo diseases are supported for now.",
                        max_length=3,
                        verbose_name="Disease Type",
                    ),
                ),
                (
                    "mondo_id",
                    models.CharField(
                        db_index=True,
                        default="",
                        help_text="The Mondo Disease Ontology ID, e.g., MONDO:0005052.",
                        max_length=26,
                        verbose_name="Mondo ID",
                    ),
                ),
                (
                    "iri",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=88,
                        verbose_name="Internationalized Resource Identifier (IRI)",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The name of the disease.",
                        max_length=256,
                        verbose_name="Name",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="When the disease was added.",
                        verbose_name="Added At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="When the disease was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The user who added the disease.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Added By",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Disease",
                "verbose_name_plural": "historical Diseases",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
