# Generated by Django 5.2.1 on 2025-07-05 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disease", "0003_alter_disease_ols_iri"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="disease",
            name="ols_iri",
        ),
        migrations.AddField(
            model_name="disease",
            name="iri",
            field=models.CharField(
                blank=True,
                default="",
                max_length=88,
                verbose_name="Internationalized Resource Identifier (IRI)",
            ),
        ),
    ]
