# Generated by Django 5.2.1 on 2025-08-19 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("disease", "0005_disease_hrid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="disease",
            name="hrid",
        ),
    ]
