- name: Ensure Bun is installed
  ansible.builtin.command:
    cmd: "curl -fsSL https://bun.sh/install | bash" # noqa: command-instead-of-module
  args:
    creates: "{{ ansible_env.HOME }}/.bun/bin/bun"
  become: false
