- name: Ensure the source code is downloaded
  ansible.builtin.git:
    repo: "{{ repo_url }}"
    version: "{{ repo_branch }}"
    dest: "{{ repo_dir }}"
- name: Ensure the Python dependencies are installed
  ansible.builtin.command:
    chdir: hla-curation-interface
    cmd: "~/.local/bin/uv sync"
  args:
    creates: "{{ repo_dir }}/.venv"
