# Generated by Django 5.2.1 on 2026-01-07 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "has_curation_permissions",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user should be able to curate.",
                        verbose_name="Curation Permissions",
                    ),
                ),
                (
                    "has_signed_phi_agreement",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user has signed the PHI agreement.",
                        verbose_name="PHI Agreement",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "db_table": "core_user_profile",
            },
        ),
    ]
