# Generated by Django 5.2.1 on 2025-06-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="firebase_sign_in_provider",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The provider used to sign the user in.",
                max_length=255,
                verbose_name="Firebase Sign-In Provider",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="firebase_display_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The user's display name from Firebase.",
                max_length=255,
                verbose_name="Firebase Display Name",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="firebase_email_verified",
            field=models.BooleanField(
                default=False,
                help_text="Whether the email address has been verified by Firebase.",
                verbose_name="Firebase Email Verified",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="firebase_photo_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="The URL of the user's profile picture from Firebase.",
                max_length=500,
                verbose_name="Firebase Photo URL",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="firebase_uid",
            field=models.CharField(
                blank=True,
                help_text="The user ID from Firebase.",
                max_length=128,
                null=True,
                unique=True,
                verbose_name="Firebase User ID",
            ),
        ),
    ]
