# Generated by Django 5.2.1 on 2026-01-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_userprofile_firebase_sign_in_provider_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="firebase_display_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="firebase_email_verified",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="firebase_photo_url",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="firebase_sign_in_provider",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="firebase_uid",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="has_curation_permissions",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user should be able to curate.",
                verbose_name="Curator",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="has_signed_phi_agreement",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user has signed the PHI agreement.",
                verbose_name="Curator",
            ),
        ),
    ]
