# Generated by Django 5.2 on 2025-05-04 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("diseases", "0001_initial"),
        ("markers", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Curation",
            fields=[
                (
                    "curation_type",
                    models.CharField(
                        help_text="The type of curation, e.g., 'allele' or 'haplotype'.",
                        max_length=255,
                        verbose_name="Curation Type",
                    ),
                ),
                (
                    "curation_id",
                    models.CharField(
                        help_text="A unique identifier for the curation.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Curation ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="new",
                        help_text="The status of the curation, e.g., 'new', 'in progress', 'done'.",
                        max_length=255,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "allele",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="markers.allele",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.curator"
                    ),
                ),
                (
                    "disease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="diseases.mondo"
                    ),
                ),
            ],
        ),
    ]
