# Generated by Django 5.2 on 2025-05-10 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("diseases", "0001_initial"),
        ("markers", "0001_initial"),
        ("publications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlleleAssociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "association_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="A unique identifier for the association for use in the HCI.",
                        max_length=3,
                        null=True,
                        unique=True,
                        verbose_name="Association ID",
                    ),
                ),
                (
                    "is_included_for_scoring",
                    models.BooleanField(
                        default=False,
                        help_text="Should this association be included for scoring?",
                        verbose_name="Include",
                    ),
                ),
                (
                    "is_conflicting_evidence",
                    models.BooleanField(
                        default=False,
                        help_text="Is the evidence in this association conflicting?",
                        verbose_name="Conflicts",
                    ),
                ),
            ],
            options={
                "verbose_name": "Allele Association",
                "verbose_name_plural": "Allele Associations",
            },
        ),
        migrations.CreateModel(
            name="AlleleCuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "curation_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="A unique identifier for the curation for use in the HCI.",
                        max_length=3,
                        null=True,
                        unique=True,
                        verbose_name="Curation ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="new",
                        help_text="The status of the curation, e.g., 'new', 'in progress', 'done'.",
                        max_length=255,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "allele",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="markers.allele",
                    ),
                ),
                (
                    "disease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="diseases.mondo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Allele Curation",
                "verbose_name_plural": "Allele Curations",
            },
        ),
        migrations.CreateModel(
            name="PubMedAlleleAssociation",
            fields=[
                (
                    "alleleassociation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="curations.alleleassociation",
                    ),
                ),
                (
                    "curation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pubmed_associations",
                        to="curations.allelecuration",
                    ),
                ),
                (
                    "pubmed_article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publications.pubmedarticle",
                        verbose_name="PubMed Article",
                    ),
                ),
            ],
            options={
                "verbose_name": "PubMed Allele Association",
                "verbose_name_plural": "PubMed Allele Associations",
            },
            bases=("curations.alleleassociation",),
        ),
    ]
