# Generated by Django 5.2 on 2025-05-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curation",
            name="curation_id",
        ),
        migrations.AddField(
            model_name="curation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="curation",
            name="curation_type",
            field=models.CharField(
                choices=[("allele", "Allele")],
                default="allele",
                help_text="The type of curation, e.g., 'allele' or 'haplotype'.",
                max_length=255,
                verbose_name="Curation Type",
            ),
        ),
    ]
