# Generated by Django 5.2 on 2025-05-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alleleassociation",
            name="zygosity",
            field=models.CharField(
                choices=[
                    ("mo", "Monoallelic (heterozygous)"),
                    ("bi", "Biallelic (homozygous)"),
                ],
                max_length=2,
                null=True,
                verbose_name="Zygosity",
            ),
        ),
    ]
