# Generated by Django 5.2 on 2025-05-05 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("curations", "0002_remove_curation_curation_id_curation_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curation",
            name="created_by",
        ),
    ]
