# Generated by Django 5.2 on 2025-05-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curations", "0002_alleleassociation_zygosity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alleleassociation",
            name="zygosity",
            field=models.CharField(
                choices=[
                    ("mo", "Monoallelic (heterozygous)"),
                    ("bi", "Biallelic (homozygous)"),
                ],
                default="mo",
                max_length=2,
                verbose_name="Zygosity",
            ),
        ),
    ]
