# Generated by Django 5.2 on 2025-05-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curations", "0003_alter_alleleassociation_zygosity"),
    ]

    operations = [
        migrations.AddField(
            model_name="alleleassociation",
            name="phase_is_confirmed",
            field=models.BooleanField(
                default=False,
                help_text="Is the phase confirmed?",
                verbose_name="Phase Confirmed",
            ),
        ),
    ]
