# Generated by Django 5.2 on 2025-05-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curations", "0003_remove_curation_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="curation",
            name="curation_id",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="A unique identifier for the curation for use in the HCI.",
                max_length=3,
                null=True,
                unique=True,
                verbose_name="Curation ID",
            ),
        ),
    ]
