# Generated by Django 5.2 on 2025-05-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curations", "0004_alleleassociation_phase_is_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="alleleassociation",
            name="typing_methods",
            field=models.CharField(
                choices=[
                    ("tag", "Tag SNPs"),
                    ("mic", "Microarrays"),
                    ("ser", "Serological"),
                    ("imp", "Imputation"),
                    ("lrt", "Low Resolution Typing"),
                    ("hrt", "High Resolution Typing"),
                    ("wes", "Whole Exome Sequencing"),
                    ("san", "Sanger Sequencing-Based Typing"),
                    ("gen", "Whole Gene Sequencing"),
                    ("nom", "Whole Genome Sequencing"),
                    ("pbn", "Panel-Based NGS (>50x coverage)"),
                ],
                default=None,
                help_text="What HLA typing methodology was used?",
                max_length=3,
                verbose_name="Typing Methods",
            ),
        ),
        migrations.AlterField(
            model_name="alleleassociation",
            name="phase_is_confirmed",
            field=models.BooleanField(
                default=False,
                help_text="Was the HLA allele phased?",
                verbose_name="Phase confirmed",
            ),
        ),
        migrations.AlterField(
            model_name="alleleassociation",
            name="zygosity",
            field=models.CharField(
                choices=[
                    ("mo", "Monoallelic (heterozygous)"),
                    ("bi", "Biallelic (homozygous)"),
                ],
                default="mo",
                max_length=2,
            ),
        ),
    ]
