# Generated by Django 5.2 on 2025-05-06 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curations", "0004_curation_curation_id"),
        ("diseases", "0001_initial"),
        ("markers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlleleCuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "curation_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="A unique identifier for the curation for use in the HCI.",
                        max_length=3,
                        null=True,
                        unique=True,
                        verbose_name="Curation ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="new",
                        help_text="The status of the curation, e.g., 'new', 'in progress', 'done'.",
                        max_length=255,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "allele",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="markers.allele",
                    ),
                ),
                (
                    "disease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="diseases.mondo"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Curation",
        ),
    ]
