# Generated by Django 5.2 on 2025-05-08 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curations", "0005_allelecuration_delete_curation"),
        ("publications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlleleAssociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "association_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="A unique identifier for the association for use in the HCI.",
                        max_length=3,
                        null=True,
                        unique=True,
                        verbose_name="Association ID",
                    ),
                ),
                (
                    "is_included_for_scoring",
                    models.BooleanField(
                        default=False,
                        help_text="Should this association be included for scoring?",
                        verbose_name="Is included for scoring?",
                    ),
                ),
                (
                    "is_conflicting_evidence",
                    models.BooleanField(
                        default=False,
                        help_text="Is the evidence in this association conflicting?",
                        verbose_name="Is conflicting evidence?",
                    ),
                ),
                (
                    "curation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="associations",
                        to="curations.allelecuration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PubMedAlleleAssociation",
            fields=[
                (
                    "alleleassociation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="curations.alleleassociation",
                    ),
                ),
                (
                    "pubmed_article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publications.pubmedarticle",
                    ),
                ),
            ],
            bases=("curations.alleleassociation",),
        ),
    ]
