# Generated by Django 5.2 on 2025-05-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curations", "0005_alleleassociation_typing_methods_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alleleassociation",
            name="typing_methods",
            field=models.CharField(
                choices=[
                    ("tag", "Tag SNPs"),
                    ("mic", "Microarrays"),
                    ("ser", "Serological"),
                    ("imp", "Imputation"),
                    ("lrt", "Low Resolution Typing"),
                    ("hrt", "High Resolution Typing"),
                    ("wes", "Whole Exome Sequencing"),
                    ("san", "Sanger Sequencing-Based Typing"),
                    ("gen", "Whole Gene Sequencing"),
                    ("nom", "Whole Genome Sequencing"),
                    ("pbn", "Panel-Based NGS (>50x coverage)"),
                ],
                default=None,
                help_text="What HLA typing methodology was used?",
                max_length=3,
                null=True,
                verbose_name="Typing Methods",
            ),
        ),
    ]
