# Generated by Django 5.2 on 2025-05-08 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curations", "0006_alleleassociation_pubmedalleleassociation"),
        ("publications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pubmedalleleassociation",
            name="pubmed_article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="publications.pubmedarticle",
            ),
        ),
    ]
