# Generated by Django 5.2 on 2025-05-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curations", "0006_alter_alleleassociation_typing_methods"),
    ]

    operations = [
        migrations.AddField(
            model_name="alleleassociation",
            name="is_gwas",
            field=models.BooleanField(
                default=False,
                help_text="Check the study was a genome-wide association study (GWAS).",
                verbose_name="GWAS",
            ),
        ),
        migrations.AddField(
            model_name="alleleassociation",
            name="p_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=30,
                default=None,
                help_text="The p-value as a decimal or in scientific notation, e.g., 5e-8.",
                max_digits=31,
                null=True,
                verbose_name="p-value",
            ),
        ),
        migrations.AlterField(
            model_name="alleleassociation",
            name="typing_methods",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tag", "Tag SNPs"),
                    ("mic", "Microarrays"),
                    ("ser", "Serological"),
                    ("imp", "Imputation"),
                    ("lrt", "Low Resolution Typing"),
                    ("hrt", "High Resolution Typing"),
                    ("wes", "Whole Exome Sequencing"),
                    ("san", "Sanger Sequencing-Based Typing"),
                    ("gen", "Whole Gene Sequencing"),
                    ("nom", "Whole Genome Sequencing"),
                    ("pbn", "Panel-Based NGS (>50x coverage)"),
                    (
                        "nop",
                        "Whole Genome Sequencing and Panel-Based NGS (>50x coverage)",
                    ),
                ],
                default=None,
                help_text="What HLA typing methodology was used?",
                max_length=3,
                null=True,
                verbose_name="Typing Method",
            ),
        ),
    ]
