# Generated by Django 5.2 on 2025-05-08 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("curations", "0007_alter_pubmedalleleassociation_pubmed_article"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alleleassociation",
            options={
                "verbose_name": "Allele Association",
                "verbose_name_plural": "Allele Associations",
            },
        ),
        migrations.AlterModelOptions(
            name="allelecuration",
            options={
                "verbose_name": "Allele Curation",
                "verbose_name_plural": "Allele Curations",
            },
        ),
        migrations.AlterModelOptions(
            name="pubmedalleleassociation",
            options={
                "verbose_name": "PubMed Allele Association",
                "verbose_name_plural": "PubMed Allele Associations",
            },
        ),
    ]
