# Generated by Django 5.2 on 2025-05-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curations", "0008_remove_alleleassociation_p_value_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alleleassociation",
            name="p_value_number",
        ),
        migrations.AddField(
            model_name="alleleassociation",
            name="multiple_testing_correction",
            field=models.CharField(
                choices=[
                    ("ov", "Overall correction for multiple testing"),
                    ("2s", "2-step p-value correction"),
                ],
                default="ov",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="alleleassociation",
            name="is_gwas",
            field=models.BooleanField(
                default=False,
                help_text="Whether the study was a genome-wide association study (GWAS).",
                verbose_name="GWAS",
            ),
        ),
    ]
