# Generated by Django 5.2 on 2025-05-13 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curations", "0009_remove_alleleassociation_p_value_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alleleassociation",
            name="multiple_testing_correction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ov", "Overall correction for multiple testing"),
                    ("2s", "2-step p-value correction"),
                ],
                default=None,
                max_length=2,
                null=True,
            ),
        ),
    ]
