# Generated by Django 5.2 on 2025-05-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curations", "0010_alter_alleleassociation_multiple_testing_correction"),
    ]

    operations = [
        migrations.AddField(
            model_name="alleleassociation",
            name="odds_ratio",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="The odds ratio as a decimal number, e.g., 0.54.",
                null=True,
                verbose_name="Odds Ratio",
            ),
        ),
    ]
