# Generated by Django 5.2 on 2025-05-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curations", "0012_alleleassociation_beta_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alleleassociation",
            name="num_cases",
            field=models.IntegerField(
                blank=True,
                default=None,
                help_text="The number of cases.",
                null=True,
                verbose_name="Cases",
            ),
        ),
        migrations.AddField(
            model_name="alleleassociation",
            name="num_controls",
            field=models.IntegerField(
                blank=True,
                default=None,
                help_text="The number of controls.",
                null=True,
                verbose_name="Controls",
            ),
        ),
        migrations.AlterField(
            model_name="alleleassociation",
            name="beta",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="The beta as a decimal number, e.g., 0.22.",
                null=True,
                verbose_name="Beta",
            ),
        ),
        migrations.AlterField(
            model_name="alleleassociation",
            name="is_gwas",
            field=models.BooleanField(
                default=False,
                help_text="Was the study a genome-wide association study?",
                verbose_name="GWAS",
            ),
        ),
    ]
