# Generated by Django 5.2 on 2025-05-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curations", "0013_alleleassociation_num_cases_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alleleassociation",
            name="has_phenotype",
            field=models.BooleanField(
                choices=[
                    ("t", "Has disease-related phenotype"),
                    ("f", "Only disease tested"),
                ],
                default="t",
                max_length=1,
                verbose_name="Has Disease-Related Phenotype",
            ),
        ),
    ]
