# Generated by Django 5.2 on 2025-05-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curations", "0015_alter_alleleassociation_has_phenotype"),
    ]

    operations = [
        migrations.AddField(
            model_name="alleleassociation",
            name="is_significant",
            field=models.BooleanField(
                default=False,
                help_text="Does this allele have a significant association with the disease?",
                verbose_name="Significant",
            ),
        ),
    ]
