# Generated by Django 5.2 on 2025-05-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curations", "0016_alleleassociation_is_significant"),
    ]

    operations = [
        migrations.AddField(
            model_name="alleleassociation",
            name="decreases_risk",
            field=models.BooleanField(
                default=False,
                help_text="Does this allele decrease the risk for getting the disease?",
                verbose_name="Decreases risk",
            ),
        ),
        migrations.AlterField(
            model_name="alleleassociation",
            name="is_significant",
            field=models.BooleanField(
                default=False,
                help_text="Does this allele have a significant association with the disease?",
                verbose_name="Significant association",
            ),
        ),
    ]
