# Generated by Django 5.2 on 2025-05-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curations", "0017_alleleassociation_decreases_risk_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alleleassociation",
            name="confidence_interval_end",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="The relative risk as a decimal number, e.g., 0.38.",
                null=True,
                verbose_name="End of Confidence Interval",
            ),
        ),
        migrations.AlterField(
            model_name="alleleassociation",
            name="confidence_interval_start",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="The relative risk as a decimal number, e.g., 0.001.",
                null=True,
                verbose_name="Start of Confidence Interval",
            ),
        ),
        migrations.AlterField(
            model_name="alleleassociation",
            name="decreases_risk",
            field=models.BooleanField(
                default=False,
                help_text="Does this allele decrease the risk of getting the disease?",
                verbose_name="Decreases risk",
            ),
        ),
    ]
