# Generated by Django 5.2 on 2025-05-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curations", "0018_alter_alleleassociation_confidence_interval_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alleleassociation",
            name="hpo_ids",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Comma-separated list of Human Phenotype Ontology IDs.",
                max_length=255,
                null=True,
                verbose_name="HPO IDs",
            ),
        ),
    ]
