- name: Set up the server for the first time
  hosts: all
  gather_facts: true
  tasks:
    - name: Admin | apt update
      ansible.builtin.include_tasks: ../tasks/admin/apt_update.yml
    - name: Admin | apt upgrade
      ansible.builtin.include_tasks: ../tasks/admin/apt_upgrade.yml
    - name: Install | uv
      ansible.builtin.include_tasks: ../tasks/install/uv.yml
    - name: Install | project
      ansible.builtin.include_tasks: ../tasks/install/project.yml
    - name: Placement | Daphne files
      ansible.builtin.include_tasks: ../tasks/placement/daphne.yml
    - name: Admin | Daphne start
      ansible.builtin.include_tasks: ../tasks/admin/daphne_start.yml
    - name: Install | Caddy
      ansible.builtin.include_tasks: ../tasks/install/caddy.yml
    - name: Placement | Caddy files
      ansible.builtin.include_tasks: ../tasks/placement/caddy.yml
    - name: Admin | Caddy start
      ansible.builtin.include_tasks: ../tasks/admin/caddy_start.yml
