---
name: "continuous integration"
on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
jobs:
  check_1_source_code_is_formatted:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "./.github/actions/install-python-dependencies"
      - uses: "extractions/setup-just@v3"
      - name: "Make sure the code is properly formatted"
        run: "just qual-src-format-check"
  check_2_source_code_is_linted:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "./.github/actions/install-python-dependencies"
      - uses: "extractions/setup-just@v3"
      - name: "Make sure the code is free of lint errors"
        run: "just qual-src-lint"
  check_3_django_check_passes:
    runs-on: "ubuntu-latest"
    env:
      DJANGO_SETTINGS_MODULE: "config.settings.prod"
      SECRET_KEY: "dummy"
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      SENTRY_ENV: "ci"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "./.github/actions/install-python-dependencies"
      - uses: "extractions/setup-just@v3"
      - name: "Run the Django check utility"
        run: "just django-check"
  check_4_tests_pass:
    runs-on: "ubuntu-latest"
    env:
      DJANGO_SETTINGS_MODULE: "config.settings.prod"
      SECRET_KEY: "dummy"
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      SENTRY_ENV: "ci"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "./.github/actions/install-python-dependencies"
      - uses: "extractions/setup-just@v3"
      - name: "Run the test suite"
        run: "just django-collectstatic && just test-all"
