---
name: "continuous integration"
on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
jobs:
  check_1_python_code_is_formatted:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "./.github/actions/install-python-dependencies"
      - uses: "extractions/setup-just@v3"
      - name: "Make sure the Python code is properly formatted"
        run: "just qual-src-format-check"
  check_2_javascript_code_is_formatted:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "./.github/actions/install-javascript-dependencies"
      - uses: "extractions/setup-just@v3"
      - name: "Make sure the JavaScript code is properly formatted"
        run: "just js-format-check"
  check_3_python_code_is_linted:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "./.github/actions/install-python-dependencies"
      - uses: "extractions/setup-just@v3"
      - name: "Make sure the Python code is free of lint errors"
        run: "just qual-src-lint"
  check_4_javascript_code_is_linted:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "./.github/actions/install-javascript-dependencies"
      - uses: "extractions/setup-just@v3"
      - name: "Make sure the JavaScript code is free of lint errors"
        run: "just js-lint"
  check_5_python_type_check_passes:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "./.github/actions/install-python-dependencies"
      - uses: "extractions/setup-just@v3"
      - name: "Make sure the Python code's type hints are correct"
        run: "just qual-src-type-check"
  check_6_django_check_passes:
    runs-on: "ubuntu-latest"
    env:
      DJANGO_SETTINGS_MODULE: "config.settings.prod"
      SECRET_KEY: "dummy"
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      SENTRY_ENV: "ci"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "./.github/actions/install-python-dependencies"
      - uses: "extractions/setup-just@v3"
      - name: "Run the Django check utility"
        run: "just django-check"
  check_7_tests_pass:
    runs-on: "ubuntu-latest"
    env:
      DJANGO_SETTINGS_MODULE: "config.settings.prod"
      SECRET_KEY: "dummy"
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      SENTRY_ENV: "ci"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "./.github/actions/install-python-dependencies"
      - uses: "./.github/actions/install-javascript-dependencies"
      - uses: "extractions/setup-just@v3"
      - name: "Run the test suite"
        run: "just django-collectstatic && just test-all"
