# Generated by Django 5.2.1 on 2026-01-07 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Allele",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        default="",
                        help_text="The human-readable ID for the object.",
                        max_length=7,
                        verbose_name="Human-Readable ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="",
                        help_text="The name of the HLA allele, e.g., DRB3*03:01:01. (The 'HLA-' part should be omitted.)",
                        max_length=60,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "car_id",
                    models.CharField(
                        blank=True,
                        help_text="ClinGen Allele Registry ID, e.g., XAHLA718827727.",
                        max_length=28,
                        null=True,
                        unique=True,
                        verbose_name="CAR ID",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the allele was added.",
                        verbose_name="Added At",
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who added the allele.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alleles_added",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Added By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Allele",
                "verbose_name_plural": "Alleles",
                "db_table": "allele",
            },
        ),
    ]
