# Generated by Django 5.2.1 on 2025-06-27 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Allele",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "car_id",
                    models.CharField(
                        default="",
                        help_text="ClinGen Allele Registry ID",
                        max_length=28,
                        unique=True,
                        verbose_name="CAR ID",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the allele was added.",
                        verbose_name="Added At",
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who added the allele.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alleles_added",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Added By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Allele",
                "verbose_name_plural": "Alleles",
                "db_table": "allele",
            },
        ),
    ]
