# Generated by Django 5.2.1 on 2025-06-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allele", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="allele",
            name="name",
            field=models.CharField(
                default="",
                help_text="The name of the HLA allele, e.g., DRB3*03:01. (The 'HLA-' part can be omitted.)",
                max_length=60,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="allele",
            name="car_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ClinGen Allele Registry ID, e.g., XAHLA718827727.",
                max_length=28,
                unique=True,
                verbose_name="CAR ID",
            ),
        ),
    ]
