# Generated by Django 5.2.1 on 2025-06-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allele", "0002_allele_name_alter_allele_car_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allele",
            name="car_id",
            field=models.CharField(
                blank=True,
                help_text="ClinGen Allele Registry ID, e.g., XAHLA718827727.",
                max_length=28,
                null=True,
                unique=True,
                verbose_name="CAR ID",
            ),
        ),
    ]
