# Generated by Django 5.2.1 on 2025-07-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allele", "0003_alter_allele_car_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allele",
            name="name",
            field=models.CharField(
                default="",
                help_text="The name of the HLA allele, e.g., DRB3*03:01:01. (The 'HLA-' part should be omitted.)",
                max_length=60,
                unique=True,
                verbose_name="Name",
            ),
        ),
    ]
