# Generated by Django 5.2.1 on 2025-08-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allele", "0005_allele_hrid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allele",
            name="hrid",
            field=models.CharField(
                default="",
                help_text="The human-readable ID for the object.",
                max_length=7,
                verbose_name="Human-Readable ID",
            ),
        ),
    ]
