# Generated by Django 5.2.1 on 2025-08-19 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("allele", "0007_alter_allele_hrid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="allele",
            old_name="hrid",
            new_name="slug",
        ),
    ]
